name: Integration Tests

on:
  schedule:
  - cron: 0 2 * * 1-5
  workflow_dispatch:

jobs:
  test-10-15-Integration-build:
    name: Run Tests 10.15
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        xcode: ["11.7", "12.4"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Unit tests
      run: make tests
      
  test-11-0-Integration-build:
    name: Run Tests 11.0
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        xcode: ["12.5.1", "13.0", "13.1", "13.2.1"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Unit tests
      run: make tests
      
  test-iOS-Xcode-macos-11:
    name: 11-XCode,iOS
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "11.7"
            iOS: "13.7"
          - xcode: "12.4"
            iOS: "14.4"
          - xcode: "12.5.1"
            iOS: "14.5"
          - xcode: "13.0"
            iOS: "15.0"
          - xcode: "13.1"
            iOS: "15.0"
          - xcode: "13.2.1"
            iOS: "15.2"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Unit tests
      run: 	xcodebuild -scheme DatadogSDKTesting_iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=${{ matrix.ios }}' test
  
  test-iOS-Xcode-macos-10:
    name: 10-XCode,iOS
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "10.3"
            iOS: "12.4"
          - xcode: "11.2.1"
            iOS: "13.2"
          - xcode: "11.5"
            iOS: "13.5"
          - xcode: "11.7"
            iOS: "13.7"
          - xcode: "12"
            iOS: "14.0"
          - xcode: "12.2"
            iOS: "14.2"
          - xcode: "12.4"
            iOS: "14.4"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Unit tests
      run: 	xcodebuild -scheme DatadogSDKTesting_iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=${{ matrix.ios }}' test

  test-Integration-macOS:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: tests macOS
      run: xcodebuild -scheme 'IntegrationTests (macOS)' test

  test-Integration-iOS:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: tests iOS
      run: xcodebuild -scheme 'IntegrationTests (iOS)' -destination 'platform=iOS Simulator,name=iPhone 8' test

  test-Integration-tvOS:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: tests tvOS
      run: xcodebuild -scheme 'IntegrationTests (tvOS)' -destination 'platform=tvOS Simulator,name=Apple TV' test
